language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get install -qq libblas-dev liblapack-dev
# command to install dependencies
install:
  - "pip install ."
# command to run tests
script: ./tests/unittests/__init__.py
